# 01_master_academic.mmd

```mermaid
flowchart TD

A[Education Level]

A --> B[Grade]

B --> C[Curriculum]

C --> D[Subject]

D --> E[Semester]

E --> F[Chapter]

F --> G[Topic]

G --> H[Sub Topic]

H --> I[Learning Objective]

I --> J[Competency]

J --> K[Bloom Taxonomy]

J --> L[Difficulty]

J --> M[Question Type]

D --> N[Language]
```