// frontend/src/components/admin/exams/exam-presets.ts
import { ExamCategory, ScoringSystem, ExamSubtestRule } from "@/types";

export interface ExamPreset {
    id: string;
    title: string;
    description: string;
    category: ExamCategory;
    scoring_system: ScoringSystem;
    duration_minutes: number;
    passing_score: number;
    grade_level: string;
    default_mode: "SANTAI" | "SIMULASI";
    badgeText: string;
    iconName: string;
    subtests: ExamSubtestRule[];
}

export const EXAM_PRESETS: ExamPreset[] = [
    {
        id: "utbk-snbt-akbar",
        title: "UTBK SNBT 2026 Akbar (IRT Standar BP3)",
        description: "Simulasi Ujian UTBK SNBT lengkap 7 subtes (TPS, Literasi Indonesia & Inggris, Penalaran Matematika) dengan penilaian Item Response Theory (IRT).",
        category: "UTBK_SNBT",
        scoring_system: "IRT",
        duration_minutes: 195,
        passing_score: 650,
        grade_level: "12 SMA / UTBK",
        default_mode: "SIMULASI",
        badgeText: "Rekomendasi UTBK",
        iconName: "Sparkles",
        subtests: [
            {
                id: "st-pu",
                subtest_name: "Penalaran Umum (PU)",
                duration_minutes: 30,
                pool_question_ids: [],
                sample_question_count: 30,
                shuffle_questions: true,
                shuffle_options: true,
            },
            {
                id: "st-pbm",
                subtest_name: "Pemahaman Bacaan & Menulis (PBM)",
                duration_minutes: 25,
                pool_question_ids: [],
                sample_question_count: 20,
                shuffle_questions: true,
                shuffle_options: true,
            },
            {
                id: "st-ppu",
                subtest_name: "Pengetahuan & Pemahaman Umum (PPU)",
                duration_minutes: 15,
                pool_question_ids: [],
                sample_question_count: 20,
                shuffle_questions: true,
                shuffle_options: true,
            },
            {
                id: "st-pk",
                subtest_name: "Pengetahuan Kuantitatif (PK)",
                duration_minutes: 20,
                pool_question_ids: [],
                sample_question_count: 15,
                shuffle_questions: true,
                shuffle_options: true,
            },
            {
                id: "st-lbi",
                subtest_name: "Literasi Bahasa Indonesia (LBI)",
                duration_minutes: 45,
                pool_question_ids: [],
                sample_question_count: 30,
                shuffle_questions: true,
                shuffle_options: true,
            },
            {
                id: "st-lbing",
                subtest_name: "Literasi Bahasa Inggris (LBING)",
                duration_minutes: 30,
                pool_question_ids: [],
                sample_question_count: 20,
                shuffle_questions: true,
                shuffle_options: true,
            },
            {
                id: "st-pm",
                subtest_name: "Penalaran Matematika (PM)",
                duration_minutes: 45,
                pool_question_ids: [],
                sample_question_count: 20,
                shuffle_questions: true,
                shuffle_options: true,
            },
        ],
    },
    {
        id: "pts-uas-paket",
        title: "PTS / UAS Paket Multi-Mapel Sekolah",
        description: "Ujian gabungan beberapa mata pelajaran (Matematika, Fisika, Kimia, dll) untuk evaluasi semester sekolah dengan skor 0-100.",
        category: "PTS_UAS",
        scoring_system: "STANDARD_POINTS",
        duration_minutes: 120,
        passing_score: 75,
        grade_level: "11 SMA",
        default_mode: "SIMULASI",
        badgeText: "Paket Sekolah",
        iconName: "Sliders",
        subtests: [
            {
                id: "st-mat",
                subtest_name: "Matematika Wajib",
                duration_minutes: 40,
                pool_question_ids: [],
                sample_question_count: 20,
                shuffle_questions: true,
                shuffle_options: true,
            },
            {
                id: "st-fis",
                subtest_name: "Fisika",
                duration_minutes: 40,
                pool_question_ids: [],
                sample_question_count: 20,
                shuffle_questions: true,
                shuffle_options: true,
            },
            {
                id: "st-kim",
                subtest_name: "Kimia",
                duration_minutes: 40,
                pool_question_ids: [],
                sample_question_count: 20,
                shuffle_questions: true,
                shuffle_options: true,
            },
        ],
    },
    {
        id: "ujian-per-mapel",
        title: "Ujian Per-Mapel / Ujian Harian (Single Mapel)",
        description: "Ujian atau latihan khusus 1 mata pelajaran spesifik untuk mengukur penguasaan materi per subjek.",
        category: "UJIAN_HARIAN",
        scoring_system: "STANDARD_POINTS",
        duration_minutes: 60,
        passing_score: 70,
        grade_level: "10 SMA",
        default_mode: "SIMULASI",
        badgeText: "Per Mapel",
        iconName: "BookOpen",
        subtests: [
            {
                id: "st-single",
                subtest_name: "Ujian Mapel Utama",
                duration_minutes: 60,
                pool_question_ids: [],
                sample_question_count: 25,
                shuffle_questions: true,
                shuffle_options: true,
            },
        ],
    },
    {
        id: "ujian-per-bab",
        title: "Drill Ujian Per-Bab (Mode Santai / Latihan)",
        description: "Latihan intensif berfokus pada 1 Bab/Topik materi tertentu dengan mode pengerjaan santai dan pembahasan langsung.",
        category: "UJIAN_BAB",
        scoring_system: "STANDARD_POINTS",
        duration_minutes: 45,
        passing_score: 80,
        grade_level: "Semua Tingkat",
        default_mode: "SANTAI",
        badgeText: "Drill Per Bab",
        iconName: "Zap",
        subtests: [
            {
                id: "st-bab",
                subtest_name: "Drill Bab Materi",
                duration_minutes: 45,
                pool_question_ids: [],
                sample_question_count: 15,
                shuffle_questions: true,
                shuffle_options: true,
            },
        ],
    },
    {
        id: "um-ptn-minus",
        title: "Ujian Mandiri PTN (Sistem Minus +4 / -1 / 0)",
        description: "Simulasi Ujian Mandiri PTN (SIMAK UI, UM UGM) mengabaikan tebakan dengan penalti nilai minus untuk jawaban salah.",
        category: "UM_PTN",
        scoring_system: "NEGATIVE_MARKING",
        duration_minutes: 150,
        passing_score: 400,
        grade_level: "12 SMA / Alumni",
        default_mode: "SIMULASI",
        badgeText: "Sistem Minus",
        iconName: "Award",
        subtests: [
            {
                id: "st-tkpa",
                subtest_name: "Kemampuan Dasar (TKPA)",
                duration_minutes: 75,
                pool_question_ids: [],
                sample_question_count: 30,
                shuffle_questions: true,
                shuffle_options: true,
            },
            {
                id: "st-saintek",
                subtest_name: "Kemampuan Saintek/Soshum",
                duration_minutes: 75,
                pool_question_ids: [],
                sample_question_count: 30,
                shuffle_questions: true,
                shuffle_options: true,
            },
        ],
    },
    {
        id: "custom-blank",
        title: "Formulir Kosong / Custom Architecture",
        description: "Mulai pembuatan ujian dari awal dengan kustomisasi total subtes, durasi, pool soal, dan aturan penilaian.",
        category: "UTBK_SNBT",
        scoring_system: "IRT",
        duration_minutes: 90,
        passing_score: 500,
        grade_level: "Umum",
        default_mode: "SIMULASI",
        badgeText: "Custom Builder",
        iconName: "PlusCircle",
        subtests: [
            {
                id: "st-custom-1",
                subtest_name: "Subtes 1",
                duration_minutes: 30,
                pool_question_ids: [],
                sample_question_count: 10,
                shuffle_questions: true,
                shuffle_options: true,
            },
        ],
    },
];
