package main

func allMapel() []mapel {
	return []mapel{
		// SD
		bind(), ipas(), mtk(),
		// SMP
		bind_smp(), bing_smp(), ipa_smp(), mtk_smp(),
		// SMA
		bind_sma(), bing_sma(), mtk_sma(),
	}
}

// SD Mapel
func bind() mapel {
	return mapel{
		LevelCode: "SD",
		Code:      "bind",
		Name:      "Bahasa Indonesia",
		Bab: []bab{
			b("Membaca Pemahaman",
				s("Menemukan Informasi Tersurat",
					[]string{"Mengidentifikasi informasi tersurat", "Menemukan fakta dalam teks", "Menentukan rincian informasi"},
					"Ide pokok", "Kalimat utama", "Kalimat penjelas", "Informasi rinci", "Fakta dalam teks", "Tokoh", "Latar", "Urutan peristiwa"),
				s("Menafsirkan Informasi",
					[]string{"Menarik kesimpulan", "Menafsirkan makna", "Menentukan pesan"},
					"Inferensi", "Simpulan", "Amanat", "Pesan moral", "Tujuan penulis", "Prediksi isi", "Hubungan sebab akibat", "Hubungan masalah dan solusi"),
				s("Analisis Isi Teks",
					[]string{"Mengevaluasi isi bacaan", "Membandingkan informasi"},
					"Fakta dan opini sederhana", "Informasi relevan", "Informasi tidak relevan", "Ringkasan", "Parafrasa sederhana")),
			b("Jenis Teks",
				s("Teks Narasi",
					[]string{"Mengidentifikasi struktur narasi"},
					"Cerita rakyat", "Dongeng", "Fabel", "Legenda", "Cerpen anak", "Cerita pengalaman"),
				s("Teks Deskripsi",
					[]string{"Mengidentifikasi objek"},
					"Deskripsi orang", "Deskripsi hewan", "Deskripsi tumbuhan", "Deskripsi tempat", "Deskripsi benda"),
				s("Teks Prosedur",
					[]string{"Memahami langkah kerja"},
					"Tujuan", "Alat dan bahan", "Langkah-langkah", "Kalimat perintah"),
				s("Teks Informasi",
					[]string{"Memahami isi teks informatif"},
					"Artikel sederhana", "Berita anak", "Ensiklopedia", "Poster informasi"),
				s("Teks Eksplanasi Sederhana",
					[]string{"Menjelaskan proses atau peristiwa"},
					"Fenomena alam", "Perubahan lingkungan", "Siklus sederhana")),
			b("Kosakata",
				s("Makna Kata",
					[]string{"Menentukan arti kata"},
					"Makna kata", "Makna dalam konteks", "Kata umum", "Kata khusus"),
				s("Hubungan Makna",
					[]string{"Membedakan hubungan antarkata"},
					"Sinonim", "Antonim", "Homonim", "Homofon", "Homograf"),
				s("Pembentukan Kata",
					[]string{"Memahami bentuk kata"},
					"Kata dasar", "Kata berimbuhan", "Awalan", "Sisipan", "Akhiran", "Gabungan imbuhan", "Kata ulang", "Kata majemuk")),
			b("Tata Bahasa",
				s("Jenis Kata",
					[]string{"Mengidentifikasi kelas kata"},
					"Kata benda", "Kata kerja", "Kata sifat", "Kata bilangan", "Kata ganti", "Kata depan", "Kata hubung", "Kata keterangan"),
				s("Struktur Kalimat",
					[]string{"Menyusun kalimat yang benar"},
					"Subjek", "Predikat", "Objek", "Pelengkap", "Keterangan", "Kalimat tunggal", "Kalimat majemuk sederhana", "Kalimat efektif"),
				s("Hubungan Antarkalimat",
					[]string{"Menyusun paragraf"},
					"Konjungsi", "Kohesi", "Koherensi", "Rujukan kata")),
			b("Ejaan dan Tanda Baca",
				s("Penulisan Kata",
					[]string{"Menggunakan ejaan yang benar"},
					"Huruf kapital", "Huruf miring", "Penulisan kata depan", "Penulisan imbuhan", "Kata baku", "Kata tidak baku"),
				s("Tanda Baca",
					[]string{"Menggunakan tanda baca"},
					"Titik", "Koma", "Titik dua", "Titik koma", "Tanda tanya", "Tanda seru", "Tanda petik", "Tanda hubung")),
			b("Menulis",
				s("Menulis Kalimat",
					[]string{"Menulis kalimat sesuai kaidah"},
					"Kalimat sederhana", "Kalimat efektif", "Pilihan kata", "Variasi kalimat"),
				s("Menulis Paragraf",
					[]string{"Menyusun paragraf"},
					"Kalimat utama", "Kalimat penjelas", "Paragraf deduktif", "Paragraf induktif"),
				s("Menulis Berbagai Jenis Teks",
					[]string{"Menulis sesuai tujuan komunikasi"},
					"Cerita pendek", "Deskripsi", "Prosedur", "Ringkasan", "Surat pribadi", "Pengumuman", "Laporan sederhana")),
			b("Menyunting",
				s("Perbaikan Bahasa",
					[]string{"Mengidentifikasi dan memperbaiki kesalahan"},
					"Kesalahan ejaan", "Kesalahan tanda baca", "Kesalahan pilihan kata", "Kesalahan struktur kalimat", "Kesalahan paragraf"),
				s("Penyempurnaan Tulisan",
					[]string{"Menyunting naskah sederhana"},
					"Konsistensi istilah", "Kejelasan informasi", "Efektivitas kalimat", "Keterpaduan paragraf")),
			b("Literasi",
				s("Literasi Informasi",
					[]string{"Mengolah informasi dari berbagai sumber"},
					"Tabel", "Grafik sederhana", "Diagram", "Infografik", "Jadwal", "Denah"),
				s("Literasi Visual",
					[]string{"Memahami informasi visual"},
					"Poster", "Komik", "Ilustrasi", "Gambar berseri", "Simbol", "Ikon")),
		},
	}
}

func ipas() mapel {
	return mapel{
		LevelCode: "SD",
		Code:      "IPAS",
		Name:      "IPAS",
		Bab: []bab{
			b("Makhluk Hidup dan Lingkungannya",
				s("Ciri-ciri Makhluk Hidup",
					[]string{"Mengidentifikasi ciri makhluk hidup", "Membedakan makhluk hidup dan benda mati"},
					"Bernapas", "Bergerak", "Tumbuh dan berkembang", "Berkembang biak", "Peka terhadap rangsang", "Memerlukan makanan", "Adaptasi dasar"),
				s("Keanekaragaman Makhluk Hidup",
					[]string{"Mengelompokkan makhluk hidup", "Mengidentifikasi habitat"},
					"Hewan vertebrata", "Hewan avertebrata", "Tumbuhan berbunga", "Tumbuhan tidak berbunga", "Habitat darat", "Habitat air", "Habitat udara", "Adaptasi morfologi", "Adaptasi fisiologi", "Adaptasi tingkah laku"),
				s("Organ Tubuh Makhluk Hidup",
					[]string{"Menjelaskan fungsi organ"},
					"Akar", "Batang", "Daun", "Bunga", "Buah", "Biji", "Organ gerak", "Organ pernapasan", "Organ pencernaan")),
			b("Sistem Tubuh Manusia",
				s("Sistem Gerak",
					[]string{"Menjelaskan fungsi alat gerak"},
					"Tulang", "Sendi", "Otot", "Kelainan tulang"),
				s("Sistem Pencernaan",
					[]string{"Menjelaskan proses pencernaan"},
					"Mulut", "Kerongkongan", "Lambung", "Usus halus", "Usus besar", "Hati", "Pankreas", "Gizi seimbang"),
				s("Sistem Pernapasan",
					[]string{"Menjelaskan mekanisme pernapasan"},
					"Hidung", "Tenggorokan", "Paru-paru", "Diafragma", "Gangguan pernapasan"),
				s("Sistem Peredaran Darah",
					[]string{"Menjelaskan fungsi sistem peredaran darah"},
					"Jantung", "Pembuluh darah", "Darah", "Golongan darah", "Menjaga kesehatan jantung"),
				s("Sistem Indra",
					[]string{"Menjelaskan fungsi alat indra"},
					"Mata", "Telinga", "Hidung", "Lidah", "Kulit")),
			b("Zat dan Perubahannya",
				s("Wujud Zat",
					[]string{"Mengidentifikasi wujud zat"},
					"Padat", "Cair", "Gas", "Sifat zat"),
				s("Perubahan Wujud",
					[]string{"Menjelaskan perubahan wujud"},
					"Mencair", "Membeku", "Menguap", "Mengembun", "Menyublim", "Mengkristal"),
				s("Campuran",
					[]string{"Membedakan campuran"},
					"Larutan", "Suspensi", "Campuran homogen", "Campuran heterogen", "Penyaringan sederhana")),
			b("Energi",
				s("Bentuk Energi",
					[]string{"Mengidentifikasi berbagai bentuk energi"},
					"Energi panas", "Energi cahaya", "Energi bunyi", "Energi listrik", "Energi gerak", "Energi kimia"),
				s("Perubahan Energi",
					[]string{"Menjelaskan perubahan energi"},
					"Listrik menjadi panas", "Listrik menjadi cahaya", "Kimia menjadi gerak", "Cahaya menjadi listrik"),
				s("Sumber Energi",
					[]string{"Mengidentifikasi sumber energi"},
					"Matahari", "Air", "Angin", "Batu bara", "Minyak bumi", "Gas alam", "Biomassa", "Energi terbarukan")),
			b("Gaya dan Gerak",
				s("Gaya",
					[]string{"Menjelaskan pengaruh gaya"},
					"Gaya dorong", "Gaya tarik", "Gaya gravitasi", "Gaya magnet", "Gaya gesek", "Gaya pegas"),
				s("Gerak",
					[]string{"Menjelaskan hubungan gaya dan gerak"},
					"Gerak lurus", "Kecepatan sederhana", "Perubahan arah", "Perubahan bentuk benda")),
			b("Bumi dan Antariksa",
				s("Tata Surya",
					[]string{"Mengenal anggota tata surya"},
					"Matahari", "Merkurius", "Venus", "Bumi", "Mars", "Jupiter", "Saturnus", "Uranus", "Neptunus"),
				s("Fenomena Alam",
					[]string{"Menjelaskan fenomena alam"},
					"Rotasi bumi", "Revolusi bumi", "Siang dan malam", "Pergantian musim", "Gerhana matahari", "Gerhana bulan", "Fase bulan"),
				s("Cuaca dan Iklim",
					[]string{"Mengidentifikasi kondisi atmosfer"},
					"Cuaca", "Iklim", "Awan", "Hujan", "Angin", "Suhu", "Kelembapan"),
				s("Bencana Alam",
					[]string{"Menjelaskan penyebab dan mitigasi bencana"},
					"Gempa bumi", "Gunung api", "Tsunami", "Banjir", "Tanah longsor", "Kekeringan", "Mitigasi bencana")),
			b("Ekologi dan Lingkungan",
				s("Ekosistem",
					[]string{"Menjelaskan komponen ekosistem"},
					"Individu", "Populasi", "Komunitas", "Ekosistem", "Biotik", "Abiotik"),
				s("Interaksi Makhluk Hidup",
					[]string{"Menganalisis hubungan antarorganisme"},
					"Simbiosis mutualisme", "Simbiosis komensalisme", "Simbiosis parasitisme", "Rantai makanan", "Jaring makanan", "Piramida makanan"),
				s("Pelestarian Lingkungan",
					[]string{"Menunjukkan perilaku menjaga lingkungan"},
					"Daur ulang", "Reduce", "Reuse", "Recycle", "Pencemaran udara", "Pencemaran air", "Pencemaran tanah", "Konservasi", "Reboisasi")),
			b("Kehidupan Bermasyarakat",
				s("Sejarah Indonesia",
					[]string{"Mengenal perkembangan sejarah bangsa"},
					"Kerajaan Hindu", "Kerajaan Buddha", "Kerajaan Islam", "Masa penjajahan", "Pergerakan nasional", "Proklamasi", "Tokoh kemerdekaan"),
				s("Geografi Indonesia",
					[]string{"Memahami kondisi geografis Indonesia"},
					"Letak geografis", "Letak astronomis", "Pulau besar", "Provinsi", "Bentang alam", "Sungai", "Gunung", "Laut"),
				s("Kegiatan Ekonomi",
					[]string{"Memahami aktivitas ekonomi"},
					"Kebutuhan", "Barang", "Jasa", "Produksi", "Distribusi", "Konsumsi", "Uang", "Pasar"),
				s("Keberagaman Indonesia",
					[]string{"Menghargai keberagaman"},
					"Suku bangsa", "Bahasa daerah", "Rumah adat", "Pakaian adat", "Tarian daerah", "Lagu daerah", "Upacara adat"),
				s("Pancasila dan Kewarganegaraan",
					[]string{"Menerapkan nilai Pancasila"},
					"Lambang negara", "Garuda Pancasila", "Lima sila Pancasila", "Hak anak", "Kewajiban anak", "Aturan", "Gotong royong", "Musyawarah")),
		},
	}
}

func mtk() mapel {
	return mapel{
		LevelCode: "SD",
		Code:      "MTK",
		Name:      "Matematika",
		Bab: []bab{
			b("Bilangan",
				s("Bilangan Bulat",
					[]string{"Membaca dan menulis bilangan bulat", "Membandingkan bilangan", "Mengurutkan bilangan", "Menggunakan garis bilangan"},
					"Nilai tempat", "Bilangan cacah", "Bilangan bulat positif", "Bilangan bulat negatif", "Membandingkan bilangan", "Mengurutkan bilangan", "Garis bilangan"),
				s("Operasi Bilangan",
					[]string{"Melakukan operasi hitung", "Menyelesaikan soal cerita"},
					"Penjumlahan", "Pengurangan", "Perkalian", "Pembagian", "Operasi campuran", "Soal cerita"),
				s("Faktor dan Kelipatan",
					[]string{"Menentukan faktor", "Menentukan kelipatan"},
					"Faktor", "Faktor prima", "Kelipatan", "FPB", "KPK", "Pohon faktor"),
				s("Pecahan",
					[]string{"Memahami berbagai bentuk pecahan", "Mengoperasikan pecahan"},
					"Pecahan biasa", "Pecahan campuran", "Pecahan senilai", "Menyederhanakan pecahan", "Membandingkan pecahan", "Penjumlahan pecahan", "Pengurangan pecahan", "Perkalian pecahan", "Pembagian pecahan"),
				s("Desimal",
					[]string{"Mengubah bentuk bilangan"},
					"Nilai tempat desimal", "Operasi desimal", "Pecahan ke desimal", "Desimal ke pecahan"),
				s("Persen",
					[]string{"Menggunakan persen"},
					"Persen", "Persen ke pecahan", "Pecahan ke persen", "Diskon sederhana"),
				s("Rasio dan Perbandingan",
					[]string{"Menentukan perbandingan"},
					"Rasio", "Perbandingan senilai", "Skala sederhana")),
			b("Aljabar Dasar",
				s("Pola Bilangan",
					[]string{"Menentukan pola"},
					"Pola gambar", "Pola bilangan", "Melanjutkan pola", "Aturan pola"),
				s("Kalimat Matematika",
					[]string{"Membuat model matematika"},
					"Simbol", "Variabel sederhana", "Persamaan sederhana")),
			b("Pengukuran",
				s("Panjang",
					[]string{"Mengukur panjang"},
					"Milimeter", "Sentimeter", "Meter", "Kilometer", "Konversi satuan"),
				s("Berat",
					nil,
					"Gram", "Kilogram", "Ons", "Ton", "Konversi berat"),
				s("Waktu",
					nil,
					"Jam", "Menit", "Detik", "Hari", "Minggu", "Bulan", "Tahun", "Kalender", "Lama waktu"),
				s("Volume",
					nil,
					"Liter", "Mililiter", "Volume kubus", "Volume balok"),
				s("Luas",
					nil,
					"Luas persegi", "Luas persegi panjang", "Luas segitiga", "Luas jajargenjang"),
				s("Keliling",
					nil,
					"Keliling persegi", "Keliling persegi panjang", "Keliling segitiga")),
			b("Geometri",
				s("Bangun Datar",
					[]string{"Mengidentifikasi bangun datar"},
					"Persegi", "Persegi panjang", "Segitiga", "Trapesium", "Jajargenjang", "Belah ketupat", "Layang-layang", "Lingkaran"),
				s("Sifat Bangun Datar",
					nil,
					"Sisi", "Sudut", "Diagonal", "Simetri lipat", "Simetri putar"),
				s("Bangun Ruang",
					[]string{"Mengenal bangun ruang"},
					"Kubus", "Balok", "Prisma", "Limas", "Tabung", "Kerucut", "Bola"),
				s("Jaring-jaring",
					nil,
					"Kubus", "Balok"),
				s("Titik Garis Bidang",
					nil,
					"Titik", "Garis", "Ruas garis", "Bidang"),
				s("Sudut",
					nil,
					"Sudut lancip", "Sudut siku-siku", "Sudut tumpul", "Mengukur sudut"),
				s("Koordinat",
					nil,
					"Koordinat sederhana", "Posisi titik")),
			b("Statistika",
				s("Penyajian Data",
					[]string{"Menyajikan data"},
					"Tabel", "Turus", "Diagram batang", "Diagram garis", "Diagram lingkaran sederhana", "Piktogram"),
				s("Analisis Data",
					[]string{"Menafsirkan data"},
					"Nilai terbesar", "Nilai terkecil", "Frekuensi", "Membaca grafik", "Perbandingan data"),
				s("Ukuran Pemusatan",
					[]string{"Menentukan ukuran pemusatan data"},
					"Mean (rata-rata)", "Median", "Modus")),
			b("Peluang Dasar",
				s("Kejadian",
					[]string{"Memahami peluang sederhana"},
					"Kejadian pasti", "Kejadian mungkin", "Kejadian mustahil", "Peluang sederhana")),
		},
	}
}

// SMP Mapel
func bind_smp() mapel {
	return mapel{
		LevelCode: "SMP",
		Code:      "bind-smp",
		Name:      "Bahasa Indonesia SMP",
		Bab: []bab{
			b("Teks Deskripsi",
				s("Konsep Teks Deskripsi",
					[]string{"Mengidentifikasi ciri teks deskripsi", "Menemukan informasi"},
					"Pengertian", "Tujuan", "Struktur", "Ciri kebahasaan"),
				s("Menelaah Isi & Menulis Teks Deskripsi",
					[]string{"Ide pokok", "Menyusun kerangka"},
					"Ide pokok", "Informasi rinci", "Kalimat deskriptif", "Kata sifat", "Menentukan objek", "Mengembangkan paragraf")),
			b("Teks Narasi & Cerita Rakyat",
				s("Cerita Naratif",
					[]string{"Memahami cerita naratif"},
					"Tokoh", "Penokohan", "Latar", "Alur", "Sudut pandang", "Amanat"),
				s("Jenis Cerita Rakyat",
					[]string{"Mengidentifikasi jenis cerita rakyat"},
					"Dongeng", "Fabel", "Legenda", "Mitos", "Hikayat sederhana")),
			b("Teks Prosedur & Surat",
				s("Teks Prosedur",
					[]string{"Memahami teks prosedur"},
					"Tujuan", "Alat dan bahan", "Langkah-langkah", "Kalimat perintah", "Konjungsi temporal"),
				s("Surat Pribadi dan Resmi",
					[]string{"Menyusun surat"},
					"Surat pribadi", "Surat resmi", "Struktur surat", "Bahasa surat")),
			b("Puisi Rakyat & Teks Berita",
				s("Puisi Rakyat",
					[]string{"Memahami puisi rakyat"},
					"Pantun", "Gurindam", "Syair", "Makna", "Amanat"),
				s("Teks Berita",
					[]string{"Menganalisis isi berita"},
					"Unsur 5W+1H", "Fakta", "Opini", "Struktur berita", "Bahasa jurnalistik")),
			b("Iklan, Slogan, Poster & Teks Eksposisi",
				s("Iklan, Slogan, Poster",
					[]string{"Memahami media informasi"},
					"Iklan", "Poster", "Slogan", "Persuasi", "Media visual"),
				s("Teks Eksposisi",
					[]string{"Menyusun argumentasi"},
					"Tesis", "Argumentasi", "Penegasan ulang", "Fakta dan opini")),
			b("Teks Eksplanasi & Ulasan",
				s("Teks Eksplanasi",
					[]string{"Menganalisis fenomena"},
					"Fenomena alam/sosial", "Sebab-akibat", "Struktur eksplanasi", "Konjungsi kausalitas"),
				s("Teks Ulasan",
					[]string{"Menyusun ulasan karya"},
					"Resensi buku", "Resensi film", "Kelebihan", "Kekurangan", "Simpulan")),
			b("Teks Laporan Hasil Observasi & Diskusi",
				s("Teks LHO",
					[]string{"Menyusun laporan observasi"},
					"Definisi umum", "Deskripsi bagian", "Simpulan", "Fakta dan data"),
				s("Teks Diskusi",
					[]string{"Menyampaikan pendapat berimbang"},
					"Isu", "Argumen pro", "Argumen kontra", "Simpulan")),
			b("Teks Persuasi, Cerpen, Drama & Pidato",
				s("Teks Persuasi & Pidato",
					[]string{"Menyampaikan pesan persuasif"},
					"Ajakan", "Argumentasi", "Struktur pidato", "Teknik berbicara"),
				s("Cerpen & Drama",
					[]string{"Memahami karya sastra"},
					"Unsur intrinsik", "Konflik", "Amanat", "Dialog", "Pementasan")),
		},
	}
}

func bing_smp() mapel {
	return mapel{
		LevelCode: "SMP",
		Code:      "bing-smp",
		Name:      "Bahasa Inggris SMP",
		Bab: []bab{
			b("Introducing Oneself & Classroom Expressions",
				s("Self & Others Introduction",
					[]string{"Memperkenalkan diri dan orang lain"},
					"Greetings", "Leave-taking", "Personal identity", "Occupation", "Nationality"),
				s("Classroom Expressions",
					[]string{"Menggunakan ungkapan kelas"},
					"Asking permission", "Giving instructions", "Classroom commands", "Classroom objects")),
			b("Describing Objects & Daily Routine",
				s("Describing People, Animals, Things",
					[]string{"Mendeskripsikan objek"},
					"Physical appearance", "Personality", "Adjectives", "Colors & Shapes"),
				s("Daily Activities & Time",
					[]string{"Menceritakan rutinitas"},
					"Daily routines", "Time & Dates", "Simple Present Tense", "Adverbs of frequency")),
			b("Descriptive & Functional Text",
				s("Descriptive Text",
					[]string{"Memahami dan menulis teks deskripsi"},
					"Generic structure", "Language features", "Main idea", "Writing & Editing"),
				s("Functional Text",
					[]string{"Memahami teks fungsional pendek"},
					"Greeting card", "Short message", "Notice", "Label", "Sign")),
			b("Recount & Narrative Text",
				s("Recount Text",
					[]string{"Menceritakan pengalaman masa lalu"},
					"Orientation", "Events", "Reorientation", "Past experiences"),
				s("Narrative Text",
					[]string{"Memahami cerita fiksi"},
					"Fairy tale", "Legend", "Fable", "Plot & Setting", "Moral value")),
			b("Procedure Text & Announcements",
				s("Procedure Text",
					[]string{"Menjelaskan langkah pembuatan/penggunaan"},
					"Goal", "Materials", "Steps", "Imperative sentences", "Sequence words"),
				s("Invitation & Announcement",
					[]string{"Menyampaikan pengumuman dan undangan"},
					"Invitation card", "School announcement", "Public information")),
			b("Report & Explanation Text",
				s("Report Text",
					[]string{"Memahami teks laporan ilmiah"},
					"General classification", "Description of facts", "Scientific report"),
				s("Explanation Text",
					[]string{"Menjelaskan fenomena alam/sosial"},
					"Natural phenomena", "Cause and effect", "Process description")),
			b("Language Focus & Grammar",
				s("Tenses & Parts of Speech",
					[]string{"Menguasai tata bahasa dasar"},
					"Simple Present", "Simple Past", "Present Continuous", "Present Perfect", "Modals", "Pronouns", "Passive Voice")),
		},
	}
}

func ipa_smp() mapel {
	return mapel{
		LevelCode: "SMP",
		Code:      "ipa-smp",
		Name:      "IPA SMP",
		Bab: []bab{
			b("Hakikat IPA & Pengukuran",
				s("Metode Ilmiah & Laboratorium",
					[]string{"Memahami hakikat IPA dan kerja ilmiah"},
					"Cabang IPA", "Sikap ilmiah", "Alat laboratorium", "Keselamatan kerja"),
				s("Pengukuran & Satuan",
					[]string{"Mengukur besaran fisika"},
					"Besaran pokok", "Besaran turunan", "Satuan SI", "Ketelitian alat ukur")),
			b("Zat, Suhu, Kalor, dan Gerak",
				s("Zat dan Perubahannya",
					[]string{"Menganalisis wujud dan sifat zat"},
					"Padat, cair, gas", "Perubahan wujud", "Campuran homogen/heterogen", "Pemisahan campuran"),
				s("Suhu, Kalor, dan Pemuaian",
					[]string{"Memahami perpindahan kalor"},
					"Skala suhu", "Konduksi", "Konveksi", "Radiasi", "Pemuaian zat"),
				s("Gerak dan Gaya",
					[]string{"Menganalisis gerak dan gaya"},
					"Kecepatan", "Percepatan", "Hukum Newton", "Gaya gesek & gravitasi")),
			b("Makhluk Hidup & Ekologi",
				s("Klasifikasi Makhluk Hidup",
					[]string{"Mengelompokkan makhluk hidup"},
					"Ciri makhluk hidup", "Kingdom", "Tata nama ilmiah", "Keanekaragaman hayati"),
				s("Ekologi & Tata Surya",
					[]string{"Memahami ekosistem dan alam semesta"},
					"Rantai makanan", "Simbiosis", "Struktur bumi", "Planet & Tata Surya")),
			b("Sistem Organ Manusia",
				s("Sistem Gerak & Pencernaan",
					[]string{"Menganalisis sistem gerak dan pencernaan"},
					"Tulang & Otot", "Sendi", "Organ pencernaan", "Enzim & Nutrisi"),
				s("Sistem Pernapasan & Peredaran Darah",
					[]string{"Menganalisis pernapasan dan sirkulasi darah"},
					"Organ pernapasan", "Mekanisme bernapas", "Jantung & Pembuluh darah", "Golongan darah")),
			b("Gelombang, Cahaya, & Tekanan",
				s("Getaran, Gelombang, dan Bunyi",
					[]string{"Memahami gelombang dan bunyi"},
					"Frekuensi & Periode", "Cepat rambat", "Resonansi", "Bunyi"),
				s("Cahaya & Alat Optik",
					[]string{"Menganalisis sifat cahaya"},
					"Pemantulan & Pembiasan", "Cermin & Lensa", "Mata & Mikroskop"),
				s("Tekanan Zat",
					[]string{"Menerapkan hukum tekanan"},
					"Tekanan hidrostatis", "Hukum Pascal", "Hukum Archimedes")),
			b("Genetika, Listrik, & Bioteknologi",
				s("Sistem Reproduksi & Pewarisan Sifat",
					[]string{"Memahami reproduksi dan genetika"},
					"Organ reproduksi", "DNA & Gen", "Persilangan Mendel"),
				s("Listrik Dinamis & Kemagnetan",
					[]string{"Menganalisis arus listrik dan magnet"},
					"Hukum Ohm", "Rangkaian seri/paralel", "Medan magnet", "Induksi elektromagnet"),
				s("Bioteknologi & Lingkungan",
					[]string{"Memahami bioteknologi dan isu lingkungan"},
					"Bioteknologi konvensional/modern", "Pencemaran lingkungan", "Konservasi & Energi terbarukan")),
		},
	}
}

func mtk_smp() mapel {
	return mapel{
		LevelCode: "SMP",
		Code:      "mtk-smp",
		Name:      "Matematika SMP",
		Bab: []bab{
			b("Bilangan & Rasio",
				s("Bilangan Bulat dan Rasional",
					[]string{"Melakukan operasi hitung bilangan"},
					"Operasi bilangan bulat", "Garis bilangan", "Pecahan biasa/campuran", "Desimal & Konversi"),
				s("Rasio dan Perbandingan",
					[]string{"Menyelesaikan soal perbandingan"},
					"Konsep rasio", "Perbandingan senilai", "Perbandingan berbalik nilai", "Skala & Peta")),
			b("Aljabar & Persamaan Linear",
				s("Bentuk Aljabar Dasar",
					[]string{"Mengoperasikan bentuk aljabar"},
					"Variabel & Koefisien", "Suku sejenis", "Perkalian aljabar"),
				s("PLSV & PtLSV",
					[]string{"Menyelesaikan persamaan linear satu variabel"},
					"Penyelesaian PLSV", "Penyelesaian PtLSV", "Model matematika")),
			b("Bentuk Aljabar Lanjut & SPLDV",
				s("Pemfaktoran Aljabar",
					[]string{"Memfaktorkan suku aljabar"},
					"Perkalian aljabar", "Pemfaktoran kuadrat", "Pecahan aljabar"),
				s("SPLDV",
					[]string{"Menyelesaikan SPLDV"},
					"Metode Eliminasi", "Metode Substitusi", "Metode Grafik", "Aplikasi SPLDV")),
			b("Fungsi Linear & Pythagoras",
				s("Fungsi Linear & Gradien",
					[]string{"Memahami fungsi linear"},
					"Relasi & Fungsi", "Grafik garis lurus", "Gradien (Kemiringan)"),
				s("Teorema Pythagoras",
					[]string{"Menerapkan teorema Pythagoras"},
					"Pembuktian Pythagoras", "Triple Pythagoras", "Segitiga siku-siku khusus")),
			b("Geometri & Bangun Ruang",
				s("Bangun Datar & Sudut",
					[]string{"Menghitung keliling dan luas"},
					"Segitiga & Segi empat", "Sudut & Garis sejajar", "Melukis geometri"),
				s("Bangun Ruang Sisi Datar",
					[]string{"Menhitung luas permukaan dan volume"},
					"Kubus & Balok", "Prisma & Limas", "Luas permukaan & Volume")),
			b("Statistika, Peluang & Transformasi",
				s("Persamaan & Fungsi Kuadrat",
					[]string{"Memahami fungsi kuadrat"},
					"Akar persamaan kuadrat", "Grafik parabola", "Nilai optimum"),
				s("Bangun Ruang Sisi Lengkung & Transformasi",
					[]string{"Menghitung bangun sisi lengkung"},
					"Tabung, Kerucut, Bola", "Translasi & Refleksi", "Rotasi & Dilatasi"),
				s("Kesebangunan & Statistika Lanjut",
					[]string{"Menganalisis kesebangunan dan data"},
					"Syarat kesebangunan", "Mean/Median/Modus", "Peluang teoritis & empiris")),
		},
	}
}

// SMA Mapel
func bind_sma() mapel {
	return mapel{
		LevelCode: "SMA",
		Code:      "bind-sma",
		Name:      "Bahasa Indonesia SMA",
		Bab: []bab{
			b("Teks Laporan Hasil Observasi & Eksposisi",
				s("Konsep & Analisis LHO",
					[]string{"Menganalisis teks LHO"},
					"Struktur LHO", "Fakta dan opini", "Definisi umum & deskripsi bagian", "Menulis LHO"),
				s("Teks Eksposisi SMA",
					[]string{"Menyusun argumen eksposisi"},
					"Tesis", "Argumentasi logis", "Data pendukung", "Bahasa persuasif")),
			b("Teks Negosiasi, Biografi, & Puisi",
				s("Teks Negosiasi & Biografi",
					[]string{"Memahami teks negosiasi dan riwayat hidup"},
					"Orientasi & Penawaran", "Keteladanan tokoh", "Kronologi peristiwa"),
				s("Puisi & Debat",
					[]string{"Menganalisis puisi dan teknik debat"},
					"Diksi & Majas", "Tema & Amanat", "Mosi debat", "Argumen & Sanggahan")),
			b("Teks Prosedur Kompleks & Eksplanasi",
				s("Teks Prosedur Kompleks",
					[]string{"Menyusun prosedur kompleks"},
					"Struktur prosedur", "Kalimat imperatif", "Konjungsi temporal"),
				s("Teks Eksplanasi & Editorial",
					[]string{"Menganalisis isu dan fenomena"},
					"Fenomena sosial/alam", "Sebab-akibat", "Isu aktual editorial", "Opini media")),
			b("Resensi, Cerpen, & Drama SMA",
				s("Resensi & Cerpen",
					[]string{"Menyusun resensi dan cerita pendek"},
					"Resensi buku/film", "Unsur intrinsik & ekstrinsik", "Nilai budaya/sosial"),
				s("Drama & Presentasi Ilmiah",
					[]string{"Menguasai pementasan dan presentasi"},
					"Dialog & Konflik", "Pementasan drama", "Slide presentasi ilmiah", "Teknik tanya jawab")),
			b("Artikel Ilmiah Populer, Makalah, & Proposal",
				s("Artikel Ilmiah Populer & Makalah",
					[]string{"Menulis karya tulis ilmiah"},
					"Struktur artikel", "Latar belakang & Rumusan masalah", "Daftar pustaka"),
				s("Proposal & Karya Ilmiah",
					[]string{"Menyusun proposal kegiatan/penelitian"},
					"Sistematika proposal", "Rencana anggaran", "Metode penelitian", "Analisis data")),
			b("Novel, Kritik Sastra, & Literasi Digital",
				s("Novel & Kritik/Esai Sastra",
					[]string{"Menganalisis karya sastra lanjut"},
					"Struktur novel", "Kritik sastra", "Esai argumentatif"),
				s("Literasi Digital & Kebahasaan Lanjut",
					[]string{"Menguji keakuratan informasi digital"},
					"Validasi hoaks", "Etika digital", "Kalimat efektif & Diksi", "Penyuntingan naskah")),
		},
	}
}

func bing_sma() mapel {
	return mapel{
		LevelCode: "SMA",
		Code:      "bing-sma",
		Name:      "Bahasa Inggris SMA",
		Bab: []bab{
			b("Interpersonal Communication & Descriptive Text",
				s("Self Identity & Expressions",
					[]string{"Berkomunikasi formal dan informal"},
					"Greetings & Introductions", "Asking/Giving Opinions", "Agreement & Disagreement"),
				s("Descriptive & Narrative Text SMA",
					[]string{"Memahami teks deskriptif dan naratif"},
					"Historical places", "Tourist attractions", "Fairy tales & Myths", "Moral values")),
			b("Announcement, Recount, & Functional Text",
				s("Announcement & Recount",
					[]string{"Memahami pengumuman dan pengalaman sejarah"},
					"School announcement", "Biography recount", "Historical events"),
				s("Functional Text SMA",
					[]string{"Memahami teks fungsional"},
					"Notice & Warning", "Poster & Advertisement", "Formal invitation card")),
			b("Analytical Exposition & Explanation Text",
				s("Analytical Exposition",
					[]string{"Menganalisis argumen kritis"},
					"Thesis statement", "Arguments & Supporting evidence", "Reiteration"),
				s("Explanation & Discussion Text",
					[]string{"Menjelaskan proses ilmiah dan isu berimbang"},
					"Scientific process", "Cause & Effect", "Pros and Cons", "Recommendations")),
			b("Formal Letters & Academic Presentation",
				s("Letters & Job Application",
					[]string{"Menulis surat resmi dan korespondensi"},
					"Formal letter", "Job application letter", "Email correspondence"),
				s("Speech & Academic Presentation",
					[]string{"Melakukan presentasi akademik"},
					"Persuasive speech", "Public speaking", "Seminar presentation", "Debate skills")),
			b("Hortatory Exposition, Review, & News Item",
				s("Hortatory Exposition & Review",
					[]string{"Menyusun persuasi dan ulasan karya"},
					"Hortatory thesis & Recommendation", "Book & Movie review", "Evaluative language"),
				s("News Item & Photo Caption",
					[]string{"Memahami berita dan infografis"},
					"Newsworthy events", "Background sources", "Caption writing")),
			b("Academic Writing & Advanced Grammar",
				s("Academic Essay & Summary",
					[]string{"Menulis esai akademik"},
					"Essay paragraph structure", "Abstract & Citation", "Summary writing"),
				s("Advanced Grammar & Structure",
					[]string{"Menguasai tata bahasa lanjut"},
					"Passive Voice", "Relative Clauses", "Conditionals Type 1-3", "Inversion & Complex Sentences")),
		},
	}
}

func mtk_sma() mapel {
	return mapel{
		LevelCode: "SMA",
		Code:      "mtk-sma",
		Name:      "Matematika SMA",
		Bab: []bab{
			b("Eksponen, Akar, Logaritma, & Fungsi",
				s("Eksponen, Akar, dan Logaritma",
					[]string{"Sifat-sifat eksponen dan logaritma"},
					"Pangkat pecahan", "Rasionalisasi akar", "Sifat logaritma", "Persamaan eksponen/logaritma"),
				s("Konsep & Operasi Fungsi",
					[]string{"Memahami relasi, fungsi, dan operasi"},
					"Domain, Kodomain, Range", "Fungsi Komposisi", "Fungsi Invers")),
			b("Persamaan, Pertidaksamaan, & Trigonometri",
				s("Persamaan & Pertidaksamaan",
					[]string{"Menyelesaikan sistem persamaan dan pertidaksamaan"},
					"SPLDV & SPLTV", "Persamaan kuadrat", "Pertidaksamaan rasional/irrasional/mutlak"),
				s("Trigonometri Dasar & Aplikasi",
					[]string{"Memahami rasio trigonometri"},
					"Radian & Derajat", "Sin, Cos, Tan, Cosec, Sec, Cot", "Sudut elevasi & depresi")),
			b("Vektor, Statistika, & Peluang",
				s("Vektor Dasar",
					[]string{"Mengoperasikan vektor"},
					"Besar & Arah Vektor", "Penjumlahan & Skalar", "Dot product"),
				s("Statistika & Kaidah Pencacahan",
					[]string{"Menghitung data dan peluang"},
					"Histogram & Ogive", "Mean/Median/Modus", "Aturan Perkalian & Faktorial", "Permutasi & Kombinasi", "Peluang Bersyarat")),
			b("Fungsi Lanjut, Matriks, & Transformasi",
				s("Fungsi Lanjut & Matriks",
					[]string{"Memahami grafik fungsi lanjut dan operasi matriks"},
					"Fungsi Kuadrat Lanjut", "Fungsi Eksponen & Logaritma", "Operasi Matriks & Invers", "SPL dengan Matriks"),
				s("Transformasi Geometri & Deret",
					[]string{"Menerapkan transformasi dan barisan"},
					"Translasi, Refleksi, Rotasi, Dilatasi", "Barisan & Deret Aritmetika/Geometri", "Deret Tak Hingga")),
			b("Limit, Turunan, & Integral",
				s("Limit & Turunan Fungsi",
					[]string{"Menghitung limit dan turunan"},
					"Limit Aljabar & Trigonometri", "Aturan Turunan", "Turunan Trigonometri/Eksponen", "Maksimum/Minimum & Optimasi"),
				s("Integral & Dimensi Tiga",
					[]string{"Menghitung integral dan geometri ruang"},
					"Integral Tak Tentu & Tentu", "Luas Daerah & Volume Putar", "Program Linear", "Dimensi Tiga (Jarak & Sudut)")),
			b("Statistika Lanjut, Peluang, & Kalkulus Ruang",
				s("Statistika Lanjut & Distribusi",
					[]string{"Menganalisis regresi dan distribusi"},
					"Regresi Linear & Korelasi", "Distribusi Binomial & Normal"),
				s("Vektor Ruang & Kalkulus Lanjut",
					[]string{"Memahami geometri ruang dan kalkulus lanjut"},
					"Vektor 3D & Cross Product", "Integral Substitusi & Parsial", "Persamaan Diferensial Sederhana")),
		},
	}
}
