package main

func allMapel() []mapel {
	return []mapel{bind(), ipas(), mtk()}
}

func bind() mapel {
	return mapel{
		Code: "bind",
		Name: "Bahasa Indonesia",
		Bab: []bab{
			b("Membaca Pemahaman",
				s("Menemukan Informasi Tersurat",
					[]string{"Mengidentifikasi informasi tersurat", "Menemukan fakta dalam teks", "Menentukan rincian informasi"},
					"Ide pokok", "Kalimat utama", "Kalimat penjelas", "Informasi rinci", "Fakta dalam teks", "Tokoh", "Latar", "Urutan peristiwa"),
				s("Menafsirkan Informasi",
					[]string{"Menarik kesimpulan", "Menafsirkan makna", "Menentukan pesan"},
					"Inferensi", "Simpulan", "Amanat", "Pesan moral", "Tujuan penulis", "Prediksi isi", "Hubungan sebab akibat", "Hubungan masalah dan solusi"),
				s("Analisis Isi Teks",
					[]string{"Mengevaluasi isi bacaan", "Membandingkan informasi"},
					"Fakta dan opini sederhana", "Informasi relevan", "Informasi tidak relevan", "Ringkasan", "Parafrasa sederhana")),
			b("Jenis Teks",
				s("Teks Narasi",
					[]string{"Mengidentifikasi struktur narasi"},
					"Cerita rakyat", "Dongeng", "Fabel", "Legenda", "Cerpen anak", "Cerita pengalaman"),
				s("Teks Deskripsi",
					[]string{"Mengidentifikasi objek"},
					"Deskripsi orang", "Deskripsi hewan", "Deskripsi tumbuhan", "Deskripsi tempat", "Deskripsi benda"),
				s("Teks Prosedur",
					[]string{"Memahami langkah kerja"},
					"Tujuan", "Alat dan bahan", "Langkah-langkah", "Kalimat perintah"),
				s("Teks Informasi",
					[]string{"Memahami isi teks informatif"},
					"Artikel sederhana", "Berita anak", "Ensiklopedia", "Poster informasi"),
				s("Teks Eksplanasi Sederhana",
					[]string{"Menjelaskan proses atau peristiwa"},
					"Fenomena alam", "Perubahan lingkungan", "Siklus sederhana")),
			b("Kosakata",
				s("Makna Kata",
					[]string{"Menentukan arti kata"},
					"Makna kata", "Makna dalam konteks", "Kata umum", "Kata khusus"),
				s("Hubungan Makna",
					[]string{"Membedakan hubungan antarkata"},
					"Sinonim", "Antonim", "Homonim", "Homofon", "Homograf"),
				s("Pembentukan Kata",
					[]string{"Memahami bentuk kata"},
					"Kata dasar", "Kata berimbuhan", "Awalan", "Sisipan", "Akhiran", "Gabungan imbuhan", "Kata ulang", "Kata majemuk")),
			b("Tata Bahasa",
				s("Jenis Kata",
					[]string{"Mengidentifikasi kelas kata"},
					"Kata benda", "Kata kerja", "Kata sifat", "Kata bilangan", "Kata ganti", "Kata depan", "Kata hubung", "Kata keterangan"),
				s("Struktur Kalimat",
					[]string{"Menyusun kalimat yang benar"},
					"Subjek", "Predikat", "Objek", "Pelengkap", "Keterangan", "Kalimat tunggal", "Kalimat majemuk sederhana", "Kalimat efektif"),
				s("Hubungan Antarkalimat",
					[]string{"Menyusun paragraf"},
					"Konjungsi", "Kohesi", "Koherensi", "Rujukan kata")),
			b("Ejaan dan Tanda Baca",
				s("Penulisan Kata",
					[]string{"Menggunakan ejaan yang benar"},
					"Huruf kapital", "Huruf miring", "Penulisan kata depan", "Penulisan imbuhan", "Kata baku", "Kata tidak baku"),
				s("Tanda Baca",
					[]string{"Menggunakan tanda baca"},
					"Titik", "Koma", "Titik dua", "Titik koma", "Tanda tanya", "Tanda seru", "Tanda petik", "Tanda hubung")),
			b("Menulis",
				s("Menulis Kalimat",
					[]string{"Menulis kalimat sesuai kaidah"},
					"Kalimat sederhana", "Kalimat efektif", "Pilihan kata", "Variasi kalimat"),
				s("Menulis Paragraf",
					[]string{"Menyusun paragraf"},
					"Kalimat utama", "Kalimat penjelas", "Paragraf deduktif", "Paragraf induktif"),
				s("Menulis Berbagai Jenis Teks",
					[]string{"Menulis sesuai tujuan komunikasi"},
					"Cerita pendek", "Deskripsi", "Prosedur", "Ringkasan", "Surat pribadi", "Pengumuman", "Laporan sederhana")),
			b("Menyunting",
				s("Perbaikan Bahasa",
					[]string{"Mengidentifikasi dan memperbaiki kesalahan"},
					"Kesalahan ejaan", "Kesalahan tanda baca", "Kesalahan pilihan kata", "Kesalahan struktur kalimat", "Kesalahan paragraf"),
				s("Penyempurnaan Tulisan",
					[]string{"Menyunting naskah sederhana"},
					"Konsistensi istilah", "Kejelasan informasi", "Efektivitas kalimat", "Keterpaduan paragraf")),
			b("Literasi",
				s("Literasi Informasi",
					[]string{"Mengolah informasi dari berbagai sumber"},
					"Tabel", "Grafik sederhana", "Diagram", "Infografik", "Jadwal", "Denah"),
				s("Literasi Visual",
					[]string{"Memahami informasi visual"},
					"Poster", "Komik", "Ilustrasi", "Gambar berseri", "Simbol", "Ikon")),
		},
	}
}

func ipas() mapel {
	return mapel{
		Code: "IPAS",
		Name: "IPAS",
		Bab: []bab{
			b("Makhluk Hidup dan Lingkungannya",
				s("Ciri-ciri Makhluk Hidup",
					[]string{"Mengidentifikasi ciri makhluk hidup", "Membedakan makhluk hidup dan benda mati"},
					"Bernapas", "Bergerak", "Tumbuh dan berkembang", "Berkembang biak", "Peka terhadap rangsang", "Memerlukan makanan", "Adaptasi dasar"),
				s("Keanekaragaman Makhluk Hidup",
					[]string{"Mengelompokkan makhluk hidup", "Mengidentifikasi habitat"},
					"Hewan vertebrata", "Hewan avertebrata", "Tumbuhan berbunga", "Tumbuhan tidak berbunga", "Habitat darat", "Habitat air", "Habitat udara", "Adaptasi morfologi", "Adaptasi fisiologi", "Adaptasi tingkah laku"),
				s("Organ Tubuh Makhluk Hidup",
					[]string{"Menjelaskan fungsi organ"},
					"Akar", "Batang", "Daun", "Bunga", "Buah", "Biji", "Organ gerak", "Organ pernapasan", "Organ pencernaan")),
			b("Sistem Tubuh Manusia",
				s("Sistem Gerak",
					[]string{"Menjelaskan fungsi alat gerak"},
					"Tulang", "Sendi", "Otot", "Kelainan tulang"),
				s("Sistem Pencernaan",
					[]string{"Menjelaskan proses pencernaan"},
					"Mulut", "Kerongkongan", "Lambung", "Usus halus", "Usus besar", "Hati", "Pankreas", "Gizi seimbang"),
				s("Sistem Pernapasan",
					[]string{"Menjelaskan mekanisme pernapasan"},
					"Hidung", "Tenggorokan", "Paru-paru", "Diafragma", "Gangguan pernapasan"),
				s("Sistem Peredaran Darah",
					[]string{"Menjelaskan fungsi sistem peredaran darah"},
					"Jantung", "Pembuluh darah", "Darah", "Golongan darah", "Menjaga kesehatan jantung"),
				s("Sistem Indra",
					[]string{"Menjelaskan fungsi alat indra"},
					"Mata", "Telinga", "Hidung", "Lidah", "Kulit")),
			b("Zat dan Perubahannya",
				s("Wujud Zat",
					[]string{"Mengidentifikasi wujud zat"},
					"Padat", "Cair", "Gas", "Sifat zat"),
				s("Perubahan Wujud",
					[]string{"Menjelaskan perubahan wujud"},
					"Mencair", "Membeku", "Menguap", "Mengembun", "Menyublim", "Mengkristal"),
				s("Campuran",
					[]string{"Membedakan campuran"},
					"Larutan", "Suspensi", "Campuran homogen", "Campuran heterogen", "Penyaringan sederhana")),
			b("Energi",
				s("Bentuk Energi",
					[]string{"Mengidentifikasi berbagai bentuk energi"},
					"Energi panas", "Energi cahaya", "Energi bunyi", "Energi listrik", "Energi gerak", "Energi kimia"),
				s("Perubahan Energi",
					[]string{"Menjelaskan perubahan energi"},
					"Listrik menjadi panas", "Listrik menjadi cahaya", "Kimia menjadi gerak", "Cahaya menjadi listrik"),
				s("Sumber Energi",
					[]string{"Mengidentifikasi sumber energi"},
					"Matahari", "Air", "Angin", "Batu bara", "Minyak bumi", "Gas alam", "Biomassa", "Energi terbarukan")),
			b("Gaya dan Gerak",
				s("Gaya",
					[]string{"Menjelaskan pengaruh gaya"},
					"Gaya dorong", "Gaya tarik", "Gaya gravitasi", "Gaya magnet", "Gaya gesek", "Gaya pegas"),
				s("Gerak",
					[]string{"Menjelaskan hubungan gaya dan gerak"},
					"Gerak lurus", "Kecepatan sederhana", "Perubahan arah", "Perubahan bentuk benda")),
			b("Bumi dan Antariksa",
				s("Tata Surya",
					[]string{"Mengenal anggota tata surya"},
					"Matahari", "Merkurius", "Venus", "Bumi", "Mars", "Jupiter", "Saturnus", "Uranus", "Neptunus"),
				s("Fenomena Alam",
					[]string{"Menjelaskan fenomena alam"},
					"Rotasi bumi", "Revolusi bumi", "Siang dan malam", "Pergantian musim", "Gerhana matahari", "Gerhana bulan", "Fase bulan"),
				s("Cuaca dan Iklim",
					[]string{"Mengidentifikasi kondisi atmosfer"},
					"Cuaca", "Iklim", "Awan", "Hujan", "Angin", "Suhu", "Kelembapan"),
				s("Bencana Alam",
					[]string{"Menjelaskan penyebab dan mitigasi bencana"},
					"Gempa bumi", "Gunung api", "Tsunami", "Banjir", "Tanah longsor", "Kekeringan", "Mitigasi bencana")),
			b("Ekologi dan Lingkungan",
				s("Ekosistem",
					[]string{"Menjelaskan komponen ekosistem"},
					"Individu", "Populasi", "Komunitas", "Ekosistem", "Biotik", "Abiotik"),
				s("Interaksi Makhluk Hidup",
					[]string{"Menganalisis hubungan antarorganisme"},
					"Simbiosis mutualisme", "Simbiosis komensalisme", "Simbiosis parasitisme", "Rantai makanan", "Jaring makanan", "Piramida makanan"),
				s("Pelestarian Lingkungan",
					[]string{"Menunjukkan perilaku menjaga lingkungan"},
					"Daur ulang", "Reduce", "Reuse", "Recycle", "Pencemaran udara", "Pencemaran air", "Pencemaran tanah", "Konservasi", "Reboisasi")),
			b("Kehidupan Bermasyarakat",
				s("Sejarah Indonesia",
					[]string{"Mengenal perkembangan sejarah bangsa"},
					"Kerajaan Hindu", "Kerajaan Buddha", "Kerajaan Islam", "Masa penjajahan", "Pergerakan nasional", "Proklamasi", "Tokoh kemerdekaan"),
				s("Geografi Indonesia",
					[]string{"Memahami kondisi geografis Indonesia"},
					"Letak geografis", "Letak astronomis", "Pulau besar", "Provinsi", "Bentang alam", "Sungai", "Gunung", "Laut"),
				s("Kegiatan Ekonomi",
					[]string{"Memahami aktivitas ekonomi"},
					"Kebutuhan", "Barang", "Jasa", "Produksi", "Distribusi", "Konsumsi", "Uang", "Pasar"),
				s("Keberagaman Indonesia",
					[]string{"Menghargai keberagaman"},
					"Suku bangsa", "Bahasa daerah", "Rumah adat", "Pakaian adat", "Tarian daerah", "Lagu daerah", "Upacara adat"),
				s("Pancasila dan Kewarganegaraan",
					[]string{"Menerapkan nilai Pancasila"},
					"Lambang negara", "Garuda Pancasila", "Lima sila Pancasila", "Hak anak", "Kewajiban anak", "Aturan", "Gotong royong", "Musyawarah")),
		},
	}
}

func mtk() mapel {
	return mapel{
		Code: "MTK",
		Name: "Matematika",
		Bab: []bab{
			b("Bilangan",
				s("Bilangan Bulat",
					[]string{"Membaca dan menulis bilangan bulat", "Membandingkan bilangan", "Mengurutkan bilangan", "Menggunakan garis bilangan"},
					"Nilai tempat", "Bilangan cacah", "Bilangan bulat positif", "Bilangan bulat negatif", "Membandingkan bilangan", "Mengurutkan bilangan", "Garis bilangan"),
				s("Operasi Bilangan",
					[]string{"Melakukan operasi hitung", "Menyelesaikan soal cerita"},
					"Penjumlahan", "Pengurangan", "Perkalian", "Pembagian", "Operasi campuran", "Soal cerita"),
				s("Faktor dan Kelipatan",
					[]string{"Menentukan faktor", "Menentukan kelipatan"},
					"Faktor", "Faktor prima", "Kelipatan", "FPB", "KPK", "Pohon faktor"),
				s("Pecahan",
					[]string{"Memahami berbagai bentuk pecahan", "Mengoperasikan pecahan"},
					"Pecahan biasa", "Pecahan campuran", "Pecahan senilai", "Menyederhanakan pecahan", "Membandingkan pecahan", "Penjumlahan pecahan", "Pengurangan pecahan", "Perkalian pecahan", "Pembagian pecahan"),
				s("Desimal",
					[]string{"Mengubah bentuk bilangan"},
					"Nilai tempat desimal", "Operasi desimal", "Pecahan ke desimal", "Desimal ke pecahan"),
				s("Persen",
					[]string{"Menggunakan persen"},
					"Persen", "Persen ke pecahan", "Pecahan ke persen", "Diskon sederhana"),
				s("Rasio dan Perbandingan",
					[]string{"Menentukan perbandingan"},
					"Rasio", "Perbandingan senilai", "Skala sederhana")),
			b("Aljabar Dasar",
				s("Pola Bilangan",
					[]string{"Menentukan pola"},
					"Pola gambar", "Pola bilangan", "Melanjutkan pola", "Aturan pola"),
				s("Kalimat Matematika",
					[]string{"Membuat model matematika"},
					"Simbol", "Variabel sederhana", "Persamaan sederhana")),
			b("Pengukuran",
				s("Panjang",
					[]string{"Mengukur panjang"},
					"Milimeter", "Sentimeter", "Meter", "Kilometer", "Konversi satuan"),
				s("Berat",
					nil,
					"Gram", "Kilogram", "Ons", "Ton", "Konversi berat"),
				s("Waktu",
					nil,
					"Jam", "Menit", "Detik", "Hari", "Minggu", "Bulan", "Tahun", "Kalender", "Lama waktu"),
				s("Volume",
					nil,
					"Liter", "Mililiter", "Volume kubus", "Volume balok"),
				s("Luas",
					nil,
					"Luas persegi", "Luas persegi panjang", "Luas segitiga", "Luas jajargenjang"),
				s("Keliling",
					nil,
					"Keliling persegi", "Keliling persegi panjang", "Keliling segitiga")),
			b("Geometri",
				s("Bangun Datar",
					[]string{"Mengidentifikasi bangun datar"},
					"Persegi", "Persegi panjang", "Segitiga", "Trapesium", "Jajargenjang", "Belah ketupat", "Layang-layang", "Lingkaran"),
				s("Sifat Bangun Datar",
					nil,
					"Sisi", "Sudut", "Diagonal", "Simetri lipat", "Simetri putar"),
				s("Bangun Ruang",
					[]string{"Mengenal bangun ruang"},
					"Kubus", "Balok", "Prisma", "Limas", "Tabung", "Kerucut", "Bola"),
				s("Jaring-jaring",
					nil,
					"Kubus", "Balok"),
				s("Titik Garis Bidang",
					nil,
					"Titik", "Garis", "Ruas garis", "Bidang"),
				s("Sudut",
					nil,
					"Sudut lancip", "Sudut siku-siku", "Sudut tumpul", "Mengukur sudut"),
				s("Koordinat",
					nil,
					"Koordinat sederhana", "Posisi titik")),
			b("Statistika",
				s("Penyajian Data",
					[]string{"Menyajikan data"},
					"Tabel", "Turus", "Diagram batang", "Diagram garis", "Diagram lingkaran sederhana", "Piktogram"),
				s("Analisis Data",
					[]string{"Menafsirkan data"},
					"Nilai terbesar", "Nilai terkecil", "Frekuensi", "Membaca grafik", "Perbandingan data"),
				s("Ukuran Pemusatan",
					[]string{"Menentukan ukuran pemusatan data"},
					"Mean (rata-rata)", "Median", "Modus")),
			b("Peluang Dasar",
				s("Kejadian",
					[]string{"Memahami peluang sederhana"},
					"Kejadian pasti", "Kejadian mungkin", "Kejadian mustahil", "Peluang sederhana")),
		},
	}
}